-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "sleepGoal" DOUBLE PRECISION NOT NULL DEFAULT 8;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "cachedInsights" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "insightsUpdatedAt" TIMESTAMP(3);
